name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find project file
        id: find-project
        run: |
          PROJECT_FILE=$(find . -name "*.csproj" -type f | head -n 1)
          echo "PROJECT_FILE=$PROJECT_FILE" >> $GITHUB_OUTPUT
          echo "Found project file: $PROJECT_FILE"

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ steps.find-project.outputs.PROJECT_FILE }}

      - name: Build the app
        run: dotnet build ${{ steps.find-project.outputs.PROJECT_FILE }} --configuration Release --no-restore

      - name: Publish the app
        run: dotnet publish ${{ steps.find-project.outputs.PROJECT_FILE }} --configuration Release --no-build -o ./publish

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            erikpajtler/rig:latest
            erikpajtler/rig:${{ github.sha }}
